name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build Utils
      run: cd ./kawa-utils && mkdir out && go build -o out/kawa-utils -v ...

    - name: Build Client
      run: cd ./kawa-client && mkdir out && go build -o out/kawa -v ...

  release:
    runs-on: ubuntu-latest
    steps:
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        path: |
            ./kawa-client/out/kawa
            ./kawa-utils/out/kawa-utils
        
