name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build Utils
      run: |
        if [ ! -e out ]; then mkdir out; fi
        cd ./kawa-utils
        go build -o ../out/kawa-utils -v *.go

    - name: Build Client
      run: |
        if [ ! -e out ]; then mkdir out; fi
        cd ./kawa-client
        go build -o ../out/kawa -v *.go

  release:
    runs-on: ubuntu-latest
    steps:
    - name: Upload Client
      uses: actions/upload-artifact@v2
      with:
        path: ./out/kawa
        
    - name: Upload Utils
      uses: actions/upload-artifact@v2
      with:
        path: ./out/kawa-utils
        
