name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build Utils
      run: |
        cd ./kawa-utils
        if [ ! -e out ]; then mkdir out; fi
        go build -o ../out/kawa-utils -v ...

    - name: Build Client
      run: |
        cd ./kawa-client
        if [ ! -e out ]; then mkdir out; fi
        go build -o ../out/kawa -v ...

  release:
    runs-on: ubuntu-latest
    steps:
    - name: Upload Client
      uses: actions/upload-artifact@v2
      with:
        path: ./kawa-client/out/kawa
    - name: Upload Utils
      uses: actions/upload-artifact@v2
      with:
        path: ./kawa-utils/out/kawa-utils
        
